### ISSUE TITLE
Consider adapt to Auditok v0.1.8

### ISSUE THREAD

**Issue by PumpkinCheshire** [BingLingGroup/autosub#137]
Auditok had stayed at v0.1.8 for 2 years. Should be very stable and useful. Downgrade the auditok when using autosub can be very frustrating.

Thanks for your hard work, this autosub is very useful.

**Comment by BingLingGroup** [comment]
It seems the higher version of Auditok doesn't have any compatibility issues. So commit https://github.com/BingLingGroup/autosub/pull/144/commits/3489be835e1d6e7a01e45308190111961c8c6fcb just simply changes the install_requires in [setup.py](https://github.com/BingLingGroup/autosub/blob/dev/setup.py).

**Comment by PumpkinCheshire** [comment]
Sorry to bother you again.

I once tried to use Auditok 0.1.8 directly, an error occurred:

Traceback (most recent call last):
  File "/usr/bin/autosub", line 33, in <module>
    sys.exit(load_entry_point('autosub==0.5.7a0', 'console_scripts',
'autosub')())
  File "/usr/lib/python3.8/site-packages/autosub/__init__.py", line 159, in
main
    cmdline_utils.audio_or_video_prcs(args,
  File "/usr/lib/python3.8/site-packages/autosub/cmdline_utils.py", line
1357, in audio_or_video_prcs
    regions = auditok_utils.auditok_gen_speech_regions(

* File "/usr/lib/python3.8/site-packages/autosub/auditok_utils.py", line
31, in auditok_gen_speech_regions
sample_width=asource.get_sample_width(),*
  File "/usr/lib/python3.8/site-packages/auditok/util.py", line 1009, in
__getattr__
    raise AttributeError(
AttributeError: 'AudioReader' has no attribute 'get_sample_width'

The error appeared in auditok_utils.py. It seems to be an easy-to-solve
function call problem, some API names may have changed.
After trying the latest dev branch, this problem still exists. Attempting
to downgrade auditok's 0.1.5 can solve this problem well.

I am very sorry for the trouble. Due to my poor python ability, it is
difficult for me to read your code and fix this problem.

Thank you for maintaining this project, this software is very important to
me.

**Comment by BingLingGroup** [comment]
It seems that I finally figure out what's going right now.
Auditok v0.1.8 which was released on 2018.11.01 is the same with the version on PyPI. If you just use pip to install Auditok latest version from PyPI, you will be all right.
But the latest [Auditok](https://github.com/amsehili/auditok) in github repo, especially the codes after commit https://github.com/amsehili/auditok/commit/f6936a308cda47a8a2ba3d08b139ad631e15ba8f, has changed some method names which was incompatible with the v0.1.8 release. More importantly it's not a stable release and the document hasn't changed since Auditok v0.1.5, especially considering most people install their Auditok by PyPI instead of directly from github. So it's not either appropriate or convenient to refactor the codes in autosub to use the new method names.
If you still want autosub to use the latest codes in Auditok, you can modify it yourself. The changes were written in the comment https://github.com/amsehili/auditok/commit/f6936a308cda47a8a2ba3d08b139ad631e15ba8f#diff-6d3f7ac4b238d7860202726f71cbc465L201-L202.

**Comment by PumpkinCheshire** [comment]
The dev branch seems no longer working because of the recently upgrade of [Auditok 0.2.0 ](https://github.com/amsehili/auditok/releases/tag/v0.2.0). Please consider restrict auditok version or try to be compatible with the new version? Also, any ideas on google's new google-cloud-speech api?

**Comment by BingLingGroup** [comment]
It's still working. The Auditok version has been restricted in the [setup.py](https://github.com/BingLingGroup/autosub/blob/dev/setup.py#L37).
